export default {
  phoenix: `Conflict (40)
Attachment (10)
3  Embrace the Void  (Tears of Amaterasu)
2  Fine Katana  (Core)
2  Ornate Fan  (Core)
3  Cloud the Mind  (Core)

Character (6)
3  Ancient Master  (Breath of the Kami)
3  Shrine Maiden  (For Honor and Glory)

Event (24)
3  Banzai!  (Core)
3  Censure  (Into the Forbidden City)
3  Court Games  (Core)
3  Let Go  (Core)
3  Supernatural Storm  (Core)
3  Against the Waves  (Core)
2  Clarity of Purpose  (Disciples of the Void)
2  Display of Power  (Core)
2  Consumed by Five Fires  (Fate Has No Secrets)
`,
  unicorn: `Conflict (40)
Attachment (7)
3  Fine Katana  (Core)
3  Force of the River  (The Ebb and Flow)
1  Talisman of the Sun  (Meditations on the Ephemeral)

Character (8)
3  Iuchi Wayfinder  (Core)
3  Shinjo Ambusher  (Children of the Empire)
2  Goblin Sneak  (Tears of Amaterasu)

Event (25)
2  A Legion of One  (Meditations on the Ephemeral)
3  Banzai!  (Core)
3  Captive Audience  (Core)
3  Defend Your Honor  (Children of the Empire)
3  Hand to Hand  (Children of the Empire)
3  Ready for Battle  (Core)
2  Unleash the Djinn  (Elements Unbound)
3  Charge!  (Core)
1  Strength in Numbers  (Core)
2  Cavalry Reserves  (Core)
`,
  dragon: `Conflict (41)
Attachment (18)
3  Fine Katana  (Core)
2  Ornate Fan  (Core)
3  Seal of the Dragon  (Meditations on the Ephemeral)
1  Ancestral Daishō  (Core)
3  Cloud the Mind  (Core)
3  Finger of Jade  (Tears of Amaterasu)
3  Reprieve  (Core)

Character (7)
2  Ancient Master  (Breath of the Kami)
2  Hiruma Skirmisher  (Into the Forbidden City)
3  Tattooed Wanderer  (Core)

Event (16)
2  Banzai!  (Core)
2  Censure  (Into the Forbidden City)
2  Court Games  (Core)
3  Hurricane Punch  (Breath of the Kami)
3  Let Go  (Core)
3  Void Fist  (All and Nothing)
1  The Mountain Does Not Fall  (Core)
`,
  crab: `Conflict (40)
Attachment (19)
2  Fine Katana  (Core)
3  Ornate Fan  (Core)
3  Cloud the Mind  (Core)
3  Reprieve  (Core)
3  Spyglass  (Core)
2  Talisman of the Sun  (Meditations on the Ephemeral)
3  Watch Commander  (Core)

Character (6)
3  Hiruma Skirmisher  (Into the Forbidden City)
3  Iuchi Wayfinder  (Core)

Event (15)
1  Banzai!  (Core)
3  Court Games  (Core)
2  Defend Your Honor  (Children of the Empire)
3  Rebuild  (Core)
3  Fight On  (The Ebb and Flow)
3  The Mountain Does Not Fall  (Core)
`,
  lion: `Conflict (40)
Attachment (5)
2  Fine Katana  (Core)
3  Ornate Fan  (Core)

Character (8)
3  Ikoma Reservist  (Tainted Lands)
3  Tattooed Wanderer  (Core)
2  Goblin Sneak  (Tears of Amaterasu)

Event (27)
3  A Legion of One  (Meditations on the Ephemeral)
1  Assassination  (Core)
3  Banzai!  (Core)
2  Censure  (Into the Forbidden City)
3  Court Games  (Core)
3  Let Go  (Core)
3  Ready for Battle  (Core)
1  Sabotage  (Tainted Lands)
3  Way of the Lion  (Core)
3  Charge!  (Core)
2  Strength in Numbers  (Core)
`,
  crane: `Conflict (40)
Attachment (4)
2  Fine Katana  (Core)
2  Ornate Fan  (Core)

Character (10)
3  Steward of Law  (Core)
2  Tattooed Wanderer  (Core)
1  Doji Fumiki  (Underhand of the Emperor)
2  Menacing Iron Warrior  (The Ebb and Flow)
2  Political Rival  (Core)

Event (26)
2  Assassination  (Core)
2  Banzai!  (Core)
2  Censure  (Into the Forbidden City)
3  Court Games  (Core)
3  For Shame!  (Core)
3  Let Go  (Core)
3  Policy Debate  (For Honor and Glory)
3  Voice of Honor  (Core)
3  Way of the Crane  (Core)
1  Admit Defeat  (Core)
1  Noble Sacrifice  (Core)
`,
  scorpion: `Conflict (40)
Attachment (4)
2  Cloud the Mind  (Core)
2  Mark of Shame  (All and Nothing)

Character (10)
2  Ancient Master  (Breath of the Kami)
2  Tattooed Wanderer  (Core)
2  Bayushi Collector  (Underhand of the Emperor)
2  Cunning Magistrate  (Fate Has No Secrets)
2  Bayushi Kachiko  (Into the Forbidden City)

Event (26)
3  Assassination  (Core)
2  Banzai!  (Core)
2  Censure  (Into the Forbidden City)
3  Court Games  (Core)
1  Duty  (Underhand of the Emperor)
3  For Shame!  (Core)
3  Forged Edict  (Core)
2  Let Go  (Core)
2  Way of the Scorpion  (Core)
2  Calling in Favors  (Core)
3  A Fate Worse Than Death  (Fate Has No Secrets)
`
}
